name: Deploy Todo App

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 13.233.103.149 >> ~/.ssh/known_hosts

      - name: Setup Ansible
        run: sudo apt update && sudo apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/deploy.yml
